### ISSUE TITLE
getting this error while running the app , windows 10 / python 3

### ISSUE THREAD

**Issue by ghost** [fez09/FPL-data-scraper#1]
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1699, in __call__
  File "FPLDataFetcher.py", line 61, in button_press
  File "FPLDataFetcher.py", line 372, in submit
  File "site-packages\requests\models.py", line 892, in json
  File "json\__init__.py", line 354, in loads
  File "json\decoder.py", line 339, in decode
  File "json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 5 column 1 (char 4)

**Comment by fez09** [comment]
I am terribly sorry for the late response. 

The code is not meant to be used at the beginning of the season. Since the cup games and the dream team stuff hasn't yet been decided. I haven't written the code to ignore those data if it is not available. 

Please use the code only at the end of the season. May/June/July. From August it won't work.
