### ISSUE TITLE
KeyError: 'leagues'

### ISSUE THREAD

**Issue by ngoduchung** [fez09/FPL-data-scraper#2]
Thanks so much for your program. IMO, your program is the best one in showing a clear view of our season.

Currently your program is throwing these error messages when I enter a team ID with H2H records. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "FPLDataFetcherx32.py", line 64, in button_press
  File "FPLDataFetcherx32.py", line 335, in submit
KeyError: 'leagues'

For team IDs without H2H records, then the program works fine. A workaround can be eliminating lines of codes which relate "H2H"

Thanks again for the program.

**Comment by ngoduchung** [comment]
Game is open now, so I will close this issue.
