### ISSUE TITLE
Key Error 'team'

### ISSUE THREAD

**Issue by Lionellanes** [fez09/FPL-data-scraper#3]
Hi, 

I'm getting this error when running this on my machine. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "FPLDataFetcherx32.py", line 64, in button_press
  File "FPLDataFetcherx32.py", line 411, in submit
KeyError: 'team'

Is there something that I'm doing wrong? 

Thanks
Andrew

**Comment by fez09** [comment]
Apologies for the delay. I prefer waiting till the end of the season before making any changes to the code. 

Code is ready for 2020/2021 Season. It should work now. 

Thanks.
